services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
    - "127.0.0.1:8123:8123"
    - "127.0.0.1:9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true
    volumes:
    - ./volumes/clickhouse/data:/var/lib/clickhouse
    - ./volumes/clickhouse/log:/var/log/clickhouse-server
    env_file: .env
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  scraper:
    build:
      context: scraper
    restart: always
    depends_on:
    - clickhouse
    env_file: .env

  ingest-worker:
    build:
      context: ingest-worker
    restart: always
    depends_on:
    - clickhouse
    env_file: .env

  api:
    build:
      context: api
    restart: always
    ports:
    - "8080:8080"
    depends_on:
    - clickhouse
    env_file: .env
