CREATE TABLE IF NOT EXISTS match_player
(
    match_id             UInt64,
    account_id           UInt64,
    player_slot          UInt8,
    team                 UInt8,
    kills                UInt8,
    deaths               UInt8,
    assists              UInt8,
    net_worth            UInt32,
    hero_id              UInt8,
    last_hits            UInt16,
    denies               UInt16,
    ability_points       UInt16,
    party                UInt8,
    assigned_lane        UInt8,
    level                UInt32,
    abandon_match_time_s UInt16,
    ability_stats        Map(Int64, Int64),
    stats_type_stat      Array(Float32),
    death_details        Nested(game_time_s UInt16,
                             killer_player_slot UInt8,
                             death_pos Tuple(Float32, Float32, Float32),
                             killer_pos Tuple(Float32, Float32, Float32),
                             death_duration_s UInt16),
    items                Nested(game_time_s UInt16,
                             item_id UInt32,
                             upgrade_id UInt64,
                             sold_time_s UInt16,
                             flags UInt8,
                             imbued_ability_id UInt64),
    stats                Nested(time_stamp_s UInt16,
                             net_worth UInt32,
                             gold_player UInt32,
                             gold_player_orbs UInt32,
                             gold_lane_creep_orbs UInt32,
                             gold_neutral_creep_orbs UInt32,
                             gold_boss UInt32,
                             gold_boss_orb UInt32,
                             gold_treasure UInt32,
                             gold_denied UInt32,
                             gold_death_loss UInt32,
                             gold_lane_creep UInt32,
                             gold_neutral_creep UInt32,
                             kills UInt8,
                             deaths UInt8,
                             assists UInt8,
                             creep_kills UInt16,
                             neutral_kills UInt16,
                             possible_creeps UInt16,
                             creep_damage UInt32,
                             player_damage UInt32,
                             neutral_damage UInt32,
                             boss_damage UInt32,
                             denies UInt16,
                             player_healing UInt32,
                             ability_points UInt16,
                             self_healing UInt32,
                             player_damage_taken UInt32,
                             max_health UInt16,
                             weapon_power UInt16,
                             tech_power UInt16,
                             shots_hit UInt16,
                             shots_missed UInt16,
                             damage_absorbed UInt32,
                             absorption_provided UInt16,
                             hero_bullets_hit UInt16,
                             hero_bullets_hit_crit UInt16,
                             heal_prevented UInt16,
                             heal_lost UInt16,
                             damage_mitigated UInt32,
                             level UInt32)
) ENGINE = MergeTree() ORDER BY match_id;
